jdk:
  - oraclejdk8

language: java

before_install:
  - rm -rf arquillian-liferay-bundle
  - pip install --user codecov

install:
  - mvn generate-test-sources

script:
  - mvn install -Pjacoco

after_success:
  - cat arquillian-extension-liferay-example/target/site/jacoco/jacoco.xml
  - codecov

after_failure:
  - cat arquillian-liferay-bundle/liferay-ce-portal-7.1.0-ga1/tomcat-9.0.6/logs/catalina.out

